export function renderLimits(limits) {
  const rows = Object.entries(limits).map(
    ([name, value]) => `| \`${name}\` | ${value.toLocaleString('en-US')} |`,
  );
  return [
    '<!-- Generated by scripts/docs-site/generate-limits.mjs from the built public DEFAULT_LIMITS export. -->',
    '# Default extraction limits',
    '',
    'These are the defaults exported by `DEFAULT_LIMITS`. Per-call overrides are available through `ExtractOptions.limits`; see the security page for how each budget is applied.',
    '',
    '| Limit | Default |',
    '|---|---:|',
    ...rows,
    '',
  ].join('\n');
}
