import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'node/index': 'src/node/index.ts',
    worker: 'src/node/worker/index.ts',
    'worker-thread': 'src/node/worker/worker.ts',
    'node/cli': 'src/node/cli/index.ts',
    doc: 'src/readers/doc/index.ts',
    txt: 'src/readers/txt/index.ts',
    markdown: 'src/readers/markdown/index.ts',
    csv: 'src/readers/csv/index.ts',
    tsv: 'src/readers/tsv/index.ts',
    json: 'src/readers/json/index.ts',
    xml: 'src/readers/xml/index.ts',
    html: 'src/readers/html/index.ts',
    rtf: 'src/readers/rtf/index.ts',
    docx: 'src/readers/docx/index.ts',
    xlsx: 'src/readers/xlsx/index.ts',
    xls: 'src/readers/xls/index.ts',
    pptx: 'src/readers/pptx/index.ts',
    odt: 'src/readers/odt/index.ts',
    zip: 'src/readers/zip/index.ts',
    gzip: 'src/readers/gzip/index.ts',
    tar: 'src/readers/tar/index.ts',
    eml: 'src/readers/eml/index.ts',
    epub: 'src/readers/epub/index.ts',
  },
  format: ['esm', 'cjs'],
  platform: 'neutral',
  target: 'es2022',
  dts: true,
  sourcemap: true,
  clean: true,
});
