import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'node/index': 'src/node/index.ts',
    worker: 'src/node/worker/index.ts',
    'worker-thread': 'src/node/worker/worker.ts',
    'node/cli': 'src/node/cli/index.ts',
    doc: 'src/readers/doc/index.ts',
    txt: 'src/readers/txt/index.ts',
    markdown: 'src/readers/markdown/index.ts',
    csv: 'src/readers/csv/index.ts',
    tsv: 'src/readers/tsv/index.ts',
    json: 'src/readers/json/index.ts',
    xml: 'src/readers/xml/index.ts',
    yaml: 'src/readers/yaml/index.ts',
    // Not a package subpath: the source-code language table the text reader loads lazily.
    'readers/code': 'src/readers/code/index.ts',
    // Not a package subpath: the compound-file (OLE) parser that detection loads for legacy files.
    ole: 'src/ole/index.ts',
    // Not a package subpath: ZIP-based format classification that detection loads for ZIP files.
    'zip-kind': 'src/detect/zip-kind.ts',
    // Not a package subpath: HTML main-content selection, loaded only with `mainContent: true`.
    'html/main-content': 'src/html/main-content.ts',
    ndjson: 'src/readers/ndjson/index.ts',
    ics: 'src/readers/ics/index.ts',
    vcf: 'src/readers/vcf/index.ts',
    srt: 'src/readers/srt/index.ts',
    vtt: 'src/readers/vtt/index.ts',
    html: 'src/readers/html/index.ts',
    rtf: 'src/readers/rtf/index.ts',
    docx: 'src/readers/docx/index.ts',
    xlsx: 'src/readers/xlsx/index.ts',
    xls: 'src/readers/xls/index.ts',
    xlsb: 'src/readers/xlsb/index.ts',
    pptx: 'src/readers/pptx/index.ts',
    odt: 'src/readers/odt/index.ts',
    ods: 'src/readers/ods/index.ts',
    odp: 'src/readers/odp/index.ts',
    image: 'src/readers/image/index.ts',
    zip: 'src/readers/zip/index.ts',
    gzip: 'src/readers/gzip/index.ts',
    tar: 'src/readers/tar/index.ts',
    eml: 'src/readers/eml/index.ts',
    msg: 'src/readers/msg/index.ts',
    epub: 'src/readers/epub/index.ts',
  },
  format: ['esm', 'cjs'],
  platform: 'neutral',
  target: 'es2022',
  dts: true,
  sourcemap: true,
  clean: true,
});
