import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtemp, readFile, readdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, relative, sep } from 'node:path';
import { test } from 'node:test';
import { generateHostiles } from './package-a-generate-hostiles.mjs';

async function inventory(root) {
  const files = [];
  async function walk(directory) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const absolute = join(directory, entry.name);
      if (entry.isDirectory()) await walk(absolute);
      else files.push([relative(root, absolute).split(sep).join('/'), await readFile(absolute)]);
    }
  }
  await walk(root);
  return files.sort(([left], [right]) => left.localeCompare(right));
}

function digest(files) {
  const hash = createHash('sha256');
  for (const [name, bytes] of files) hash.update(name).update('\0').update(bytes).update('\0');
  return hash.digest('hex');
}

test('hostile generator output is deterministic and has a CC0 note for every fixture', async () => {
  const first = await mkdtemp(join(tmpdir(), 'docsluice-hostile-a-'));
  const second = await mkdtemp(join(tmpdir(), 'docsluice-hostile-b-'));
  try {
    await generateHostiles(first);
    await generateHostiles(second);
    const generated = await inventory(join(first, 'hostile/package-a'));
    const regenerated = await inventory(join(second, 'hostile/package-a'));
    assert.equal(digest(generated), digest(regenerated));
    const assets = generated.filter(([name]) => !name.endsWith('.license'));
    assert.ok(assets.length >= 25, `expected at least 25 hostile assets, received ${assets.length}`);
    const licenses = new Map(generated.filter(([name]) => name.endsWith('.license')));
    assert.equal(licenses.size, assets.length);
    for (const [name] of assets) {
      const license = licenses.get(`${name}.license`);
      assert.ok(license, `missing licence for ${name}`);
      const text = license.toString('utf8');
      assert.match(text, /^SPDX-License-Identifier: CC0-1\.0\n/);
      assert.match(text, /Source: generated by scripts\/hostile\/package-a-generate-hostiles\.mjs/);
      assert.match(text, /Requirements: SEC-/);
    }
  } finally {
    await rm(first, { recursive: true, force: true });
    await rm(second, { recursive: true, force: true });
  }
});

test('hostile manifest delta covers SEC-1 through SEC-10 with bounded fixture bytes', async () => {
  const root = await mkdtemp(join(tmpdir(), 'docsluice-hostile-manifest-'));
  try {
    await generateHostiles(root);
    const delta = JSON.parse(await readFile(join(root, 'scripts/hostile/package-a-manifest-delta.json'), 'utf8'));
    assert.ok(Array.isArray(delta.entries));
    const requirements = new Set(delta.entries.flatMap((entry) => entry.requirements));
    for (let id = 1; id <= 10; id += 1) assert.ok(requirements.has(`SEC-${id}`), `missing SEC-${id}`);
    for (const entry of delta.entries) {
      assert.equal(entry.file.includes('..'), false, `unsafe path ${entry.file}`);
      assert.equal(entry.extraction, 'blocked: extract() is not present in foundation 10ae498');
    }
    const assets = (await inventory(join(root, 'hostile/package-a'))).filter(([name]) => !name.endsWith('.license'));
    const totalBytes = assets.reduce((sum, [, bytes]) => sum + bytes.length, 0);
    assert.ok(totalBytes <= 3 * 1024 * 1024, `generated assets exceed 3 MiB: ${totalBytes}`);
    for (const [name, bytes] of assets) assert.ok(bytes.length <= 2 * 1024 * 1024, `${name} exceeds per-file cap`);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
