const fs=require('fs'); const http=require('http'); const path=require('path');
const { chromium }=require(process.env.PDF_SPIKE_PLAYWRIGHT || '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=process.env.PDF_SPIKE_FIXTURE_DIR || '/workspace/package-e-preparation/pdf-fixtures/generated';
const names=['labels-outline-links.pdf','two-columns.pdf','image-only.pdf','text-100-pages.pdf','hostile/actions.pdf'];
const fixtures={}; for(const n of names) fixtures[n]=fs.readFileSync(path.join(root,n)).toString('base64');
const html=`<!doctype html><meta charset="utf-8"><title>pending</title><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self' 'nonce-local-probe'; connect-src 'none'; worker-src 'none'; object-src 'none'; base-uri 'none'"><pre id="result">pending</pre><script type="importmap" nonce="local-probe">{"imports":{"unpdf/pdfjs":"/unpdf/pdfjs.mjs"}}</script><script type="module" nonce="local-probe">
const attempts={fetch:0,worker:0,eval:0,function:0,xhr:0};
globalThis.fetch=(...a)=>{attempts.fetch++;throw Error('fetch blocked')};globalThis.Worker=class{constructor(){attempts.worker++;throw Error('Worker blocked')}};globalThis.XMLHttpRequest=class{constructor(){attempts.xhr++;throw Error('XHR blocked')}};globalThis.eval=(...a)=>{attempts.eval++;throw Error('eval blocked')};const NativeFunction=globalThis.Function;globalThis.Function=new Proxy(NativeFunction,{apply(){attempts.function++;throw Error('Function blocked')},construct(){attempts.function++;throw Error('Function blocked')}});
try{const api=await import('/unpdf/index.mjs');const pdfjs=await api.getResolvedPDFJS();const legacy=await import('/legacy/pdf.mjs');const modes=[];const fixtures=${JSON.stringify(fixtures)};for(const [mode,engine,open] of [['unpdf',pdfjs,(bytes)=>api.getDocumentProxy(bytes,{isEvalSupported:false,useWorkerFetch:false,useWasm:false,disableAutoFetch:true,disableStream:true,verbosity:0})],['legacy',legacy,(bytes)=>legacy.getDocument({data:bytes,isEvalSupported:false,useWorkerFetch:false,useWasm:false,disableAutoFetch:true,disableStream:true,verbosity:0}).promise]]){const results=[];for(const [name,b64] of Object.entries(fixtures)){const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const doc=await open(bytes);let chars=0;for(let i=1;i<=doc.numPages;i++){const pg=await doc.getPage(i);const t=await pg.getTextContent();chars+=t.items.reduce((n,x)=>n+('str'in x?x.str.length:0),0);await pg.cleanup()}results.push({name,pages:doc.numPages,chars});await doc.destroy()}modes.push({mode,engineVersion:engine.version,results})}document.querySelector('#result').textContent=JSON.stringify({ok:true,modes,attempts});document.title=document.querySelector('#result').textContent}catch(e){document.querySelector('#result').textContent=JSON.stringify({ok:false,error:String(e),stack:e?.stack,attempts});document.title=document.querySelector('#result').textContent}
</script>`;
const unpdf=process.env.PDF_SPIKE_UNPDF_DIR || '/tmp/docsluice-pdf-spike/node_modules/unpdf/dist';
const legacy=process.env.PDF_SPIKE_PDFJS_DIR || '/tmp/docsluice-pdf-spike/node_modules/pdfjs-dist/legacy/build';
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://127.0.0.1');let body,type;if(u.pathname==='/'){body=html;type='text/html'}else if(u.pathname==='/unpdf/index.mjs'){body=fs.readFileSync(path.join(unpdf,'index.mjs'));type='text/javascript'}else if(u.pathname==='/unpdf/pdfjs.mjs'){body=fs.readFileSync(path.join(unpdf,'pdfjs.mjs'));type='text/javascript'}else if(u.pathname==='/legacy/pdf.mjs'){body=fs.readFileSync(path.join(legacy,'pdf.mjs'));type='text/javascript'}else if(u.pathname==='/legacy/pdf.worker.mjs'){body=fs.readFileSync(path.join(legacy,'pdf.worker.mjs'));type='text/javascript'}else{res.writeHead(404);return res.end('not found')}res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-store'});res.end(body)});
server.listen(0,'127.0.0.1',async()=>{const address=server.address();let browser;const log={requests:[],console:[],errors:[]};try{browser=await chromium.launch({headless:true,executablePath:process.env.PDF_SPIKE_CHROMIUM || '/usr/bin/chromium',args:['--no-sandbox']});log.chromium=browser.version();const page=await browser.newPage();page.on('request',r=>log.requests.push(r.url()));page.on('console',m=>log.console.push(`${m.type()}: ${m.text()}`));page.on('pageerror',e=>log.errors.push(String(e)));await page.goto(`http://127.0.0.1:${address.port}/`,{waitUntil:'domcontentloaded',timeout:10000});const stop=Date.now()+25000;while(Date.now()<stop){log.result=await page.title();if(log.result && log.result!=='pending')break;await page.waitForTimeout(250)}}catch(e){log.error=String(e)}finally{if(browser)await browser.close();server.close(()=>{fs.writeFileSync('/workspace/package-e-preparation/pdf/spike/chromium-loopback-result.json',JSON.stringify(log,null,2));console.log(JSON.stringify(log,null,2))})}});
